// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using oop.AppDbContext;

#nullable disable

namespace oop.Migrations
{
    [DbContext(typeof(RecordDbContext))]
    [Migration("20220720164323_releaseyearandtracks")]
    partial class releaseyearandtracks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("oop.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Black Sabbath"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Judas Priest"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Iron Maiden"
                        });
                });

            modelBuilder.Entity("oop.Models.Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ReleaseYear")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Records");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            Genre = 0,
                            Name = "Heaven and Hell",
                            ReleaseYear = "1980",
                            SerialNumber = "9102 752"
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 3,
                            Genre = 0,
                            Name = "Piece of Mind",
                            ReleaseYear = "1983",
                            SerialNumber = "9102 752"
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 2,
                            Genre = 0,
                            Name = "Defenders of the Faith",
                            ReleaseYear = "1984",
                            SerialNumber = "9102 752"
                        });
                });

            modelBuilder.Entity("oop.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Condition = 110,
                            Price = 0,
                            RecordId = 1
                        },
                        new
                        {
                            Id = 2,
                            Condition = 101,
                            Price = 0,
                            RecordId = 1
                        });
                });

            modelBuilder.Entity("oop.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<int>("TrackNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecordId");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Neon Knights",
                            RecordId = 1,
                            TrackNo = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Children of the Sea",
                            RecordId = 1,
                            TrackNo = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Die with your boots on",
                            RecordId = 2,
                            TrackNo = 4
                        },
                        new
                        {
                            Id = 3,
                            Name = "The Trooper",
                            RecordId = 2,
                            TrackNo = 5
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rock Hard Ride Free",
                            RecordId = 3,
                            TrackNo = 3
                        },
                        new
                        {
                            Id = 6,
                            Name = "The Sentinel",
                            RecordId = 3,
                            TrackNo = 4
                        });
                });

            modelBuilder.Entity("oop.Models.Record", b =>
                {
                    b.HasOne("oop.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("oop.Models.Track", b =>
                {
                    b.HasOne("oop.Models.Record", null)
                        .WithMany("Tracks")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("oop.Models.Record", b =>
                {
                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
