// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using oop.AppDbContext;

#nullable disable

namespace oop.Migrations
{
    [DbContext(typeof(RecordDbContext))]
    [Migration("20230217182343_PostRecords6")]
    partial class PostRecords6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("oop.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Black Sabbath"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Judas Priest"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Iron Maiden"
                        },
                        new
                        {
                            Id = 4,
                            Name = "The Beatles"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pink Floyd"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Motorhead"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Michael Jackson"
                        },
                        new
                        {
                            Id = 8,
                            Name = "The Rolling Stones"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Deep Purple"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Rainbow"
                        });
                });

            modelBuilder.Entity("oop.Models.Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int?>("Genre")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ReleaseYear")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Records");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            Genre = 0,
                            GenreId = 0,
                            ImageUrl = "https://i.discogs.com/VXXKjs87ESPmntp4jgYGQv-Q16EKJQnBGdX0NF-1vys/rs:fit/g:sm/q:90/h:594/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTY3NzMz/Ny0xMzMyNzQ4NTk1/LmpwZWc.jpeg",
                            Name = "Heaven and Hell",
                            ReleaseYear = "1980",
                            SerialNumber = "9102 752"
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 3,
                            Genre = 0,
                            GenreId = 0,
                            ImageUrl = "https://i.discogs.com/VyqY8388sgwjGVc25Z6FQbLLgXlmPgyGL7AkYrfgidA/rs:fit/g:sm/q:90/h:600/w:598/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE4Mzk4/NDItMTU5MDE1MzU5/My02MTc3LmpwZWc.jpeg",
                            Name = "Piece of Mind",
                            ReleaseYear = "1983",
                            SerialNumber = "9102 752"
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 2,
                            Genre = 0,
                            GenreId = 0,
                            ImageUrl = "https://i.discogs.com/bxSIVqkuJrEplrBi4gkZNJA5hEllnwN-q_r7PYS5T8o/rs:fit/g:sm/q:90/h:599/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM3MjMx/Mi0xNTkwMzE5NjY4/LTU2NDkuanBlZw.jpeg",
                            Name = "Defenders of the Faith",
                            ReleaseYear = "1984",
                            SerialNumber = "9102 752"
                        },
                        new
                        {
                            Id = 112,
                            ArtistId = 5,
                            Genre = 1,
                            GenreId = 0,
                            ImageUrl = "https://i.discogs.com/9TFRqx1yW7EkC71l42QR2UEjnSWzcXT5TGDsfWxT4xE/rs:fit/g:sm/q:90/h:600/w:597/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE4NzMw/MTMtMTY2NzIwODk0/MC01NTc3LmpwZWc.jpeg",
                            Name = "Dark Side of the Moon",
                            ReleaseYear = "1973",
                            SerialNumber = "91 7"
                        },
                        new
                        {
                            Id = 113,
                            ArtistId = 10,
                            Genre = 1,
                            GenreId = 0,
                            ImageUrl = "https://i.discogs.com/rNwD19S4NSiDrD6lTyzZYatIQ-YJ9hy0m4MGqqqtD94/rs:fit/g:sm/q:90/h:498/w:500/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ0ODM3/NDktMTM2NjE4Mjg4/NS0xMjA2LmpwZWc.jpeg",
                            Name = "Rising",
                            ReleaseYear = "1976",
                            SerialNumber = "9111 7"
                        },
                        new
                        {
                            Id = 115,
                            ArtistId = 7,
                            Genre = 2,
                            GenreId = 0,
                            ImageUrl = "https://i.discogs.com/dWe2AyguSxJpaaEWbK_mVLL3zs2ejuta0sJCx5BvS8o/rs:fit/g:sm/q:90/h:600/w:597/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI5MTEy/OTMtMTU5NDI0NTgx/Mi03OTMxLmpwZWc.jpeg",
                            Name = "Thriller",
                            ReleaseYear = "1982",
                            SerialNumber = "92111 7"
                        });
                });

            modelBuilder.Entity("oop.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecordId");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Condition = 1,
                            Price = 99m,
                            RecordId = 1
                        },
                        new
                        {
                            Id = 2,
                            Condition = 2,
                            Price = 32m,
                            RecordId = 1
                        },
                        new
                        {
                            Id = 3,
                            Condition = 0,
                            Price = 32m,
                            RecordId = 2
                        },
                        new
                        {
                            Id = 4,
                            Condition = 1,
                            Price = 32m,
                            RecordId = 3
                        },
                        new
                        {
                            Id = 5,
                            Condition = 5,
                            Price = 32m,
                            RecordId = 3
                        });
                });

            modelBuilder.Entity("oop.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<int>("TrackNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecordId");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Neon Knights",
                            RecordId = 1,
                            TrackNo = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Children of the Sea",
                            RecordId = 1,
                            TrackNo = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Die with your boots on",
                            RecordId = 2,
                            TrackNo = 4
                        },
                        new
                        {
                            Id = 3,
                            Name = "The Trooper",
                            RecordId = 2,
                            TrackNo = 5
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rock Hard Ride Free",
                            RecordId = 3,
                            TrackNo = 3
                        },
                        new
                        {
                            Id = 6,
                            Name = "The Sentinel",
                            RecordId = 3,
                            TrackNo = 4
                        });
                });

            modelBuilder.Entity("oop.Models.Record", b =>
                {
                    b.HasOne("oop.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("oop.Models.Stock", b =>
                {
                    b.HasOne("oop.Models.Record", "Record")
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("oop.Models.Track", b =>
                {
                    b.HasOne("oop.Models.Record", null)
                        .WithMany("Tracks")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("oop.Models.Record", b =>
                {
                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
